# Generated by Django 3.1.4 on 2020-12-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20201207_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='uploaded_file',
            new_name='upload_file',
        ),
    ]
